# SPDX-FileCopyrightText: 2023 Birger Schacht <birger.schacht@oeaw.ac.at>
# SPDX-License-Identifier: MIT
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: apis-acdhch-default-settings
      - uses: actions/checkout@v4
      - run: gh workflow run publish.yml
        env:
          GH_TOKEN: ${{ github.token }}
        if: ${{ steps.release.outputs.release_created }}
